// Gia tri mac dinh khop CHINH XAC voi seed 2 migration:
//   supabase/migrations/20260706000003_seed_app_settings.sql (seed goc)
//   supabase/migrations/20260706120000_phase2_labels.sql (nhan Phase 2, merge vao labels)
// Dung cho nut "Khoi phuc mac dinh" tung muc o trang Cai dat — ghi de dung
// key tuong ung (labels / group_defaults / interaction_types / video_domains /
// warning_days) len app_settings, KHONG dung an cu che seed migration.

import type { AppSettings } from './types'

export const DEFAULT_SETTINGS: AppSettings = {
  labels: {
    app_name: 'PersonalCRM',
    groups: {
      gia_dinh: 'Gia đình',
      ban_be: 'Bạn bè',
      doi_tac: 'Đối tác',
      dong_nghiep: 'Đồng nghiệp',
      con_cai: 'Con cái',
      khac: 'Khác',
    },
    interaction_types: {
      gap_mat: 'Gặp mặt',
      goi_dien: 'Gọi điện',
      nhan_tin: 'Nhắn tin',
      du_lich: 'Du lịch',
      an_uong: 'Ăn uống',
      cong_viec: 'Công việc',
      khac: 'Khác',
    },
    roles: {
      admin: 'Quản trị',
      editor: 'Biên tập',
      viewer: 'Chỉ xem',
    },
    nav: {
      dashboard: 'Tổng quan',
      contacts: 'Danh bạ',
      map: 'Sơ đồ',
      giapha: 'Gia phả',
      reminders: 'Nhắc nhở',
      groups: 'Nhóm',
      settings: 'Cài đặt',
      menu: 'Menu',
      import: 'Nhập danh bạ',
    },
    dashboard: {
      greeting: 'Xin chào',
      sap_nguoi: 'Sắp nguội — cần giữ liên lạc',
      favorites: 'Ưa thích',
      recent: 'Hoạt động gần đây',
      birthdays: 'Sinh nhật tháng này',
      stats: 'Thống kê',
      top_groups: 'Nhóm nổi bật',
      need_attention: 'mối quan hệ cần chú ý',
    },
    person: {
      profile: 'Hồ sơ',
      info: 'Thông tin',
      timeline: 'Dòng thời gian',
      gallery: 'Ảnh & Video',
      social: 'Mạng xã hội',
      keep_in_touch: 'Giữ liên lạc',
      notes: 'Ghi chú riêng tư',
      gift_ideas: 'Ý tưởng quà tặng',
      how_we_met: 'Quen nhau thế nào',
      preferences: 'Sở thích & kiêng kỵ',
      hobbies: 'Sở thích',
      tags: 'Thẻ',
      birthday: 'Sinh nhật',
      phone: 'Điện thoại',
      email: 'Email',
      company: 'Công ty',
      job_title: 'Chức danh',
      address: 'Địa chỉ',
      hometown: 'Quê quán',
      locked_field: '🔒 Chỉ Admin/Editor',
      favorite: 'Ưa thích',
      last_contact: 'Tương tác gần nhất',
      no_contact_yet: 'Chưa có tương tác',
      in_family_tree: 'Thuộc dòng họ',
      gender: 'Giới tính',
      gender_nam: 'Nam',
      gender_nu: 'Nữ',
      deceased: 'Đã mất',
      death_date: 'Ngày mất (dương lịch)',
      death_lunar: 'Ngày giỗ (âm lịch)',
      burial_place: 'Mộ phần',
      biography: 'Tiểu sử',
      lunar_suffix: 'ÂL',
      giapha_not_migrated:
        'Đã lưu hồ sơ, nhưng các trường gia phả chưa lưu được — cơ sở dữ liệu chưa nâng cấp (chạy migration gia phả để kích hoạt).',
    },
    giapha: {
      title: 'Gia phả',
      tree: 'Cây gia phả',
      members: 'Thành viên dòng họ',
      generation: 'Đời',
      unlinked: 'Chưa nối vào cây',
      unlinked_hint: 'Thêm quan hệ gia đình trong hồ sơ để nối người này vào cây.',
      upcoming_gio: 'Giỗ sắp tới',
      no_gio: 'Chưa có ngày giỗ nào được ghi.',
      side_chong: 'Phía chồng',
      side_vo: 'Phía vợ',
      side_chung: 'Con cháu chung',
      side_prefix: 'Phía',
      add_members: 'Thêm thành viên',
      remove_member: 'Bỏ khỏi dòng họ',
      remove_confirm: 'Bỏ người này khỏi dòng họ? Hồ sơ và quan hệ vẫn giữ nguyên.',
      empty: 'Chưa có thành viên nào trong dòng họ. Bấm "Thêm thành viên" để bắt đầu.',
      root_couple: 'Cặp gốc',
      days_left: 'còn',
      days_unit: 'ngày',
      show_all: 'Xem tất cả',
      export_png: 'Xuất ảnh PNG',
      print: 'In',
    },
    actions: {
      add: 'Thêm',
      edit: 'Sửa',
      delete: 'Xóa',
      save: 'Lưu',
      cancel: 'Hủy',
      search: 'Tìm kiếm...',
      quick_add: 'Ghi nhanh',
      add_person: 'Thêm liên hệ',
      add_interaction: 'Thêm tương tác',
      upload_photo: 'Tải ảnh lên',
      add_video_link: 'Dán link video',
      login: 'Đăng nhập',
      logout: 'Đăng xuất',
      confirm_delete: 'Bạn chắc chắn muốn xóa?',
    },
    status: {
      on_track: 'Ổn định',
      due_soon: 'Sắp đến hạn',
      overdue: 'Quá hạn',
      no_reminder: 'Không nhắc',
    },
    quick_add: {
      step_person: 'Chọn người',
      step_type: 'Loại tương tác',
      step_note: 'Ghi chú',
      success: 'Đã ghi tương tác',
    },
    auth: {
      email: 'Email',
      password: 'Mật khẩu',
      email_placeholder: 'ban@email.com',
      password_placeholder: '••••••••',
      login_button: 'Đăng nhập',
      signing_in: 'Đang đăng nhập...',
      subtitle: 'Đăng nhập để tiếp tục',
      wrong_credentials: 'Email hoặc mật khẩu không đúng',
      welcome: 'Chào mừng trở lại',
    },
    empty: {
      no_persons: 'Chưa có liên hệ nào',
      no_results: 'Không tìm thấy kết quả',
      no_interactions: 'Chưa có tương tác',
      no_media: 'Chưa có ảnh/video',
      coming_soon: 'Sắp ra mắt',
    },
    import: {
      title: 'Nhập danh bạ từ Google Contacts',
      step_upload: 'Chọn file',
      step_preview: 'Xem trước & đối chiếu',
      step_result: 'Kết quả',
      drop_hint: 'Kéo thả hoặc bấm để chọn file CSV',
      not_csv: 'Chỉ nhận file .csv',
      wrong_format: 'File không đúng định dạng Google Contacts CSV',
      total: 'Tổng số dòng',
      will_insert: 'Thêm mới',
      will_update: 'Cập nhật (trùng)',
      has_error: 'Dòng lỗi',
      run: 'Bắt đầu nhập',
      importing: 'Đang nhập...',
      done: 'Nhập xong',
      inserted: 'Đã thêm',
      updated: 'Đã cập nhật',
      failed: 'Lỗi',
      download_errors: 'Tải danh sách lỗi',
      row: 'Dòng',
      reason: 'Lý do',
      no_identity: 'Thiếu cả tên lẫn số điện thoại',
      try_again: 'Nhập file khác',
    },
    table: {
      view_card: 'Thẻ',
      view_table: 'Bảng',
      name: 'Tên',
      group: 'Nhóm',
      phone: 'SĐT',
      email: 'Email',
      tags: 'Tags',
      frequency: 'Nhịp',
      last_contact: 'Lần cuối',
      status: 'Trạng thái',
      selected: 'đã chọn',
      select_all: 'Chọn tất cả',
      page: 'Trang',
      no_frequency: 'Không nhắc',
      saved: 'Đã lưu',
      save_error: 'Lỗi lưu, đã hoàn tác',
    },
    bulk: {
      change_group: 'Đổi nhóm',
      add_tag: 'Gán tag',
      set_frequency: 'Gán nhịp',
      delete: 'Xóa',
      apply: 'Áp dụng',
      with_default_freq: 'Gán kèm nhịp mặc định theo nhóm',
      tag_placeholder: 'Nhập tag...',
      done: 'Đã cập nhật',
      clear: 'Bỏ chọn',
    },
    settings: {
      title: 'Cài đặt',
      labels: 'Nhãn hiển thị',
      group_defaults: 'Nhịp mặc định theo nhóm',
      interaction_types: 'Loại tương tác',
      video_domains: 'Domain video cho phép',
      warning_days: 'Số ngày cảnh báo sắp nguội',
      users: 'Người dùng & Phân quyền',
      password: 'Đổi mật khẩu',
      save: 'Lưu thay đổi',
      saved: 'Đã lưu — hiệu lực ngay',
      restore: 'Khôi phục mặc định',
      restored: 'Đã khôi phục',
      add: 'Thêm',
      remove: 'Xóa',
      enabled: 'Bật',
      add_type: 'Thêm loại',
      add_domain: 'Thêm domain',
      days_unit: 'ngày',
      role: 'Vai trò',
      cannot_demote_self: 'Không thể tự hạ quyền chính mình',
      admin_only: 'Chỉ quản trị viên truy cập được trang này',
      unsaved: 'Có thay đổi chưa lưu',
    },
    password: {
      new_password: 'Mật khẩu mới',
      confirm: 'Nhập lại mật khẩu',
      change: 'Đổi mật khẩu',
      changed: 'Đã đổi mật khẩu',
      mismatch: 'Mật khẩu nhập lại không khớp',
      too_short: 'Mật khẩu tối thiểu 8 ký tự',
    },
  },
  group_defaults: {
    gia_dinh: 30,
    ban_be: 90,
    doi_tac: 30,
    dong_nghiep: 60,
    con_cai: 30,
    khac: 180,
  },
  interaction_types: [
    { value: 'gap_mat', label: 'Gặp mặt', enabled: true },
    { value: 'goi_dien', label: 'Gọi điện', enabled: true },
    { value: 'nhan_tin', label: 'Nhắn tin', enabled: true },
    { value: 'du_lich', label: 'Du lịch', enabled: true },
    { value: 'an_uong', label: 'Ăn uống', enabled: true },
    { value: 'cong_viec', label: 'Công việc', enabled: true },
    { value: 'khac', label: 'Khác', enabled: true },
  ],
  video_domains: [
    'drive.google.com',
    'photos.google.com',
    'photos.app.goo.gl',
    'youtube.com',
    'youtu.be',
  ],
  warning_days: 7,
}
